"""Write or check the carrier cell of the vision-language retrieval workshop notebook.

The workshop notebook carries two files byte-for-byte and verifies their SHA-256 before use:

* ``retrieval_workshop.py``  <- ``tools/retrieval_workshop.py`` (every model stage), and
* ``requirements.lock.txt``  <- ``tools/retrieval-workshop-requirements.lock`` (``uv pip compile
  --generate-hashes`` output for CPython 3.12 on ``x86_64-manylinux_2_28``).

Each carried string is written as an implicitly concatenated run of pieces of at most 1,000
characters, split at line boundaries, so no notebook line is long enough to stall the Colab editor.
Only the carrier cell (id ``uvcarrier``) and ``metadata.dimer.carried_files`` are touched.

Usage::

    python tools/build_retrieval_workshop_carrier.py          # rewrite the carrier cell
    python tools/build_retrieval_workshop_carrier.py --check  # exit 1 if the notebook is stale
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = ROOT / "tutorials" / "DIMER_MultiModel_Vision_Language_Retrieval_Workshop.ipynb"
CARRIER_ID = "uvcarrier"
CARRIED = {
    "retrieval_workshop.py": ROOT / "tools" / "retrieval_workshop.py",
    "requirements.lock.txt": ROOT / "tools" / "retrieval-workshop-requirements.lock",
}
PIECE_LIMIT = 1000


def pieces(text: str, limit: int = PIECE_LIMIT) -> list[str]:
    out: list[str] = []
    current = ""
    for line in text.splitlines(keepends=True):
        if current and len(current) + len(line) > limit:
            out.append(current)
            current = ""
        current += line
    if current:
        out.append(current)
    return out


def carried_texts() -> dict[str, str]:
    texts = {}
    for name, path in CARRIED.items():
        data = path.read_bytes()
        if b"\r" in data:
            raise SystemExit(f"{path} must use LF line endings")
        texts[name] = data.decode("utf-8")
    return texts


def carried_hashes(texts: dict[str, str]) -> dict[str, str]:
    return {name: hashlib.sha256(text.encode("utf-8")).hexdigest() for name, text in texts.items()}


def carrier_source(texts: dict[str, str]) -> str:
    lines = [
        "# @title Carried stage file and hash lock (infrastructure)",
        "# Generated by tools/build_retrieval_workshop_carrier.py; do not edit by hand.",
        "CARRIED_FILES = {",
    ]
    for name, text in texts.items():
        lines.append(f" {name!r}: (")
        lines.extend(f"  {piece!r}" for piece in pieces(text))
        lines.append(" ),")
    lines.append("}")
    hashes = carried_hashes(texts)
    lines.append("CARRIED_HASHES = {")
    lines.extend(f" {name!r}: {digest!r}," for name, digest in hashes.items())
    lines.append("}")
    lines += [
        "RUNNER_ROOT = WORK_ROOT / 'runner'",
        "for name, text in CARRIED_FILES.items():",
        "    path = RUNNER_ROOT / name",
        "    path.parent.mkdir(parents=True, exist_ok=True)",
        "    path.write_text(text, encoding='utf-8', newline='\\n')",
        "    if __import__('hashlib').sha256(path.read_bytes()).hexdigest()"
        " != CARRIED_HASHES[name]:",
        "        raise RuntimeError('Carried file integrity failure: ' + name)",
        "print('Carried stage file and hash lock verified:', sorted(CARRIED_FILES))",
    ]
    return "\n".join(lines)


def to_source_list(source: str) -> list[str]:
    return source.splitlines(keepends=True)


def render(notebook: dict) -> dict:
    texts = carried_texts()
    cells = [c for c in notebook["cells"] if c.get("id") == CARRIER_ID]
    if len(cells) != 1:
        raise SystemExit(f"expected exactly one cell with id {CARRIER_ID!r}, found {len(cells)}")
    cells[0]["source"] = to_source_list(carrier_source(texts))
    dimer = notebook["metadata"]["dimer"]
    dimer["carried_files"] = {
        name: {"source": CARRIED[name].relative_to(ROOT).as_posix(), "sha256": digest}
        for name, digest in carried_hashes(texts).items()
    }
    return notebook


def dump(notebook: dict) -> str:
    return json.dumps(notebook, indent=2, ensure_ascii=False)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="fail if the notebook carrier is stale"
    )
    args = parser.parse_args(argv)
    current = NOTEBOOK.read_text(encoding="utf-8")
    expected = dump(render(json.loads(current)))
    if args.check:
        if current != expected:
            print(f"STALE: {NOTEBOOK.name} carrier differs from tools/; run without --check")
            return 1
        print(f"OK: {NOTEBOOK.name} carrier matches {', '.join(sorted(CARRIED))}")
        return 0
    NOTEBOOK.write_bytes(expected.encode("utf-8"))
    print(f"wrote {NOTEBOOK.name} ({len(expected.encode('utf-8'))} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
